Add before_and_after to moreitertools
omnilib/aioitertools pull request #111
Opened 2022-05-20 14:16 UTC by danielkza

### Description

Add before_and_after functin to moreitertools

2022-05-20 22:50 UTC, jreese commented
Please rebase onto latest from main to resolve some of these build issues.

2022-05-22 13:38 UTC, danielkza commented
rebased

2022-05-23 04:44 UTC, jreese requested changes
Overall looks good, just needs some changes to pass CI on 3.6 :)

2022-05-23 04:44 UTC, jreese commented on aioitertools/more_itertools.py
> +    transition = asyncio.get_running_loop().create_future()
This uses APIs that aren't available on 3.6. `asyncio.get_event_loop()` should be sufficient.

2022-05-23 16:33 UTC, jreese approved these changes

2022-05-23 16:33 UTC, merged

2022-05-23 16:33 UTC, jreese commented
Thank you!